
CREATE TABLE `USER_PROFILE` (
  `UUID` varchar(36) NOT NULL,
  `EMAIL_ADDRESS` varchar(75) NOT NULL,
  `FIRST_NAME` varchar(75) NOT NULL,
  `LAST_NAME` varchar(75) NOT NULL,
  `CREATE_TS` datetime NOT NULL,
  `LAST_MODIFIED_TS` datetime DEFAULT NULL,
  `LAST_LOGGED_TS` datetime DEFAULT NULL,
  `ACTIVE_FLAG` char(1) NOT NULL DEFAULT 'Y',
  `ROLE_ID` int(11) NOT NULL DEFAULT '2',
  PRIMARY KEY (`UUID`),
  UNIQUE KEY `UI_user_profile_email_address` (`EMAIL_ADDRESS`),
  KEY `IDX_user_profile_name` (`LAST_NAME`,`FIRST_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `USER_PROFILE` WRITE;
INSERT INTO `USER_PROFILE` VALUES ('a56ca76a-faa3-4374-87fe-e825c43fb91a','me@gmail.com','Admin','Admin','2017-05-20 18:20:28','2017-06-11 22:02:37','2017-06-11 19:17:16','Y',1);
UNLOCK TABLES;

CREATE TABLE `USER_CREDENTIAL` (
  `UUID` varchar(36) NOT NULL,
  `PASSWORD` varchar(200) NOT NULL,
  `LAST_MODIFIED_TS` datetime DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  KEY `FK_FTLN_user_cred_user_profile_idx` (`UUID`),
  CONSTRAINT `FK_FTLN_user_cred_user_profile` FOREIGN KEY (`UUID`) REFERENCES `USER_PROFILE` (`UUID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `USER_CREDENTIAL` WRITE;
INSERT INTO `USER_CREDENTIAL` VALUES ('a56ca76a-faa3-4374-87fe-e825c43fb91a','AEKHVrVMIdYk0sgcAM0pRLXZs3dpQMG1','2017-05-20 18:20:54');
UNLOCK TABLES;

CREATE TABLE `USER_ROLE` (
  `ID` int(11) NOT NULL,
  `ROLE` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=big5;

LOCK TABLES `USER_ROLE` WRITE;
INSERT INTO `USER_ROLE` VALUES (1,'ADMIN'),(2,'USER');
UNLOCK TABLES;

CREATE TABLE `USER_TOKEN` (
  `TOKEN_UUID` varchar(36) NOT NULL,
  `EMAIL_ADDRESS` varchar(75) NOT NULL,
  `CREATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `LAST_MODIFIED_TS` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `USER_UUID` varchar(36) NOT NULL,
  PRIMARY KEY (`TOKEN_UUID`),
  KEY `IDX_USER_NAME` (`EMAIL_ADDRESS`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

